# 89. Find the Difference
# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:
# Input: s = "", t = "y"
# Output: "y"
# Constraints:
#     0 <= s.length <= 1000
#     t.length == s.length + 1
#     s and t consist of lowercase English letters.

from collections import Counter
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_count = Counter(s)
        for char in t:
            if char not in s_count or s_count[char] == 0:
                return char
            s_count[char] -= 1
        return ""
    
    
# class Solution:
#     def findTheDifference(self, s: str, t: str) -> str:
#         sum_t = 0
#         sum_s = 0
#         # finding the total assci of s
#         for char in s:
#             sum_s += ord(char)
#         # adding the total assci sum of t
#         for char in t:
#             sum_t += ord(char)
#         # find the total difference of this character and substracted this sum
#         extra_char_ascii = sum_t - sum_s
#         return chr(extra_char_ascii)
